const CHEERPJ_LOADER_URL = 'https://cjrtnc.leaningtech.com/4.2/loader.js'
const RANDOMIZER_DEBUG_KEY = 'pokemon:randomizer-debug'
const RANDOMIZER_VERBOSE_KEY = 'pokemon:randomizer-verbose'
const RANDOMIZER_SETTINGS_VERSION = 322
const CRC32_TABLE = buildCrc32Table()
const EMULATOR_HEAP_GLOBAL_KEYS = [
  'HEAP8',
  'HEAP16',
  'HEAP32',
  'HEAP64',
  'HEAPU8',
  'HEAPU16',
  'HEAPU32',
  'HEAPU64',
  'HEAPF32',
  'HEAPF64',
] as const

function debugLog(...args: unknown[]): void {
  if (window.localStorage.getItem(RANDOMIZER_VERBOSE_KEY) === 'true') {
    console.log(...args)
  }
}

export type RandomizerPresetId = 'classic' | 'balanced' | 'chaos'

export interface RandomizerPreset {
  id: RandomizerPresetId
  label: string
  description: string
  settingsPath: string
}

export const RANDOMIZER_PRESETS: RandomizerPreset[] = [
  {
    id: 'classic',
    label: 'Classic Randomizer',
    description: 'Random starters, wilds, trainers, and statics without the full chaos stack.',
    settingsPath: 'randomizer/settings/classic.rnqs',
  },
  {
    id: 'balanced',
    label: 'Balanced Randomizer',
    description: 'A steadier preset with more guardrails than classic while still reshuffling the run.',
    settingsPath: 'randomizer/settings/balanced.rnqs',
  },
  {
    id: 'chaos',
    label: 'Chaos Randomizer',
    description: 'The loud upstream race preset with far less balance protection.',
    settingsPath: 'randomizer/settings/chaos.rnqs',
  },
]

declare global {
  interface Window {
    cheerpjInit?: () => Promise<void>
    cheerpjRunLibrary?: (path: string) => Promise<CheerpJLibrary>
  }
}

type CheerpJLibrary = Record<string, unknown>

let loaderPromise: Promise<void> | null = null
let runtimePromise: Promise<CheerpJLibrary> | null = null
let emulatorHeapGlobalsSnapshot: Partial<Record<(typeof EMULATOR_HEAP_GLOBAL_KEYS)[number], unknown>> | null = null

interface RandomizerDebugState {
  startedAt: string
  updatedAt: string
  phase: string
  currentStep: string
  completedSteps: string[]
  error: string | null
  preset: RandomizerPresetId
  romName: string
  romBytes: number
  settingsPath?: string
  sourcePath?: string
  outputPath?: string
  telemetry: {
    moduleHeap8Length: number | null
    windowHeap8Length: number | null
    jsHeapLimit: number | null
    usedJsHeapSize: number | null
    totalJsHeapSize: number | null
  }
}

export async function randomizeRom({
  romData,
  romName,
  preset,
  presetLabel: presetLabelOverride,
  settingsOverride,
  onStatus,
}: {
  romData: Uint8Array
  romName: string
  preset: RandomizerPresetId
  presetLabel?: string
  settingsOverride?: string
  onStatus?: (message: string) => void
}): Promise<{ fileName: string; fileData: Uint8Array; presetLabel: string }> {
  try {
    const presetConfig = RANDOMIZER_PRESETS.find((option) => option.id === preset)
    if (!presetConfig) {
      throw new Error('Unknown randomizer preset.')
    }

    const debug = createRandomizerDebugState({
      preset,
      romName,
      romBytes: romData.byteLength,
    })

    onStatus?.('Preparing the browser randomizer...')
    const lib = await runRandomizerStep(debug, 'ensure-runtime-ready', () => ensureRuntimeReady())
    await runRandomizerStep(debug, 'clear-randomizer-storage', () => clearRandomizerStorage())

    const sourceFileName = buildSourceFileName(romName)
    const outputFileName = buildOutputFileName(romName, preset)
    const workingSourcePath = `/files/${sourceFileName}`
    const outputPath = `/files/${outputFileName}`
    debug.sourcePath = workingSourcePath
    debug.outputPath = outputPath
    persistRandomizerDebugState(debug)

    onStatus?.(`Applying ${presetLabelOverride ?? presetConfig.label}...`)
    let normalizedSettingsString: string
    if (settingsOverride) {
      normalizedSettingsString = await runRandomizerStep(debug, 'use-settings-override', async () => settingsOverride)
    } else {
      onStatus?.('Loading preset settings...')
      const settingsBytes = await runRandomizerStep(debug, 'fetch-preset-settings', () =>
        loadPresetSettings(presetConfig.settingsPath),
      )

      const decodedPreset = await runRandomizerStep(debug, 'decode-preset-settings', () =>
        decodePresetSettings(settingsBytes),
      )
      normalizedSettingsString = await runRandomizerStep(debug, 'normalize-preset-settings', async () => {
        if (decodedPreset.version > RANDOMIZER_SETTINGS_VERSION) {
          throw new Error('The bundled preset was generated by a newer randomizer version.')
        }

        return updateSettingsString(decodedPreset.version, decodedPreset.settingsString)
      })
    }
    onStatus?.('Generating a fresh randomized Platinum ROM...')
    const javaRandom = await runRandomizerStep(debug, 'create-java-rng', async () => {
      const Random = await resolveJavaClass<new () => unknown>(lib, ['java', 'util', 'Random'])
      return await new Random()
    })
    const romHandler = await runRandomizerStep(debug, 'create-rom-handler', () =>
      createJavaInstance(lib, ['com', 'dabomstew', 'pkrandom', 'romhandlers', 'Gen4RomHandler'], javaRandom),
    )
    await runRandomizerStep(
      debug,
      'stage-working-source-file',
      () => stageWorkingSourceFile(lib, workingSourcePath, romData),
      600000,
    )
    const sourceFile = await runRandomizerStep(debug, 'inspect-working-source-file', () =>
      createJavaInstance(lib, ['java', 'io', 'File'], workingSourcePath),
    )
    await runRandomizerStep(debug, 'verify-working-source-file', async () => {
      const exists = Boolean(await callJavaMethod(sourceFile, 'exists'))
      const length = Number(await callJavaMethod(sourceFile, 'length'))
      if (!exists || Number(length) <= 0) {
        throw new Error(`Working source ROM is not readable (${String(exists)} / ${String(length)}).`)
      }
    })
    const randomAccessFile = await runRandomizerStep(debug, 'probe-working-source-random-access', () =>
      createJavaInstance(lib, ['java', 'io', 'RandomAccessFile'], workingSourcePath, 'r'),
    )
    await runRandomizerStep(debug, 'verify-working-source-header', () => verifyWorkingSourceHeader(randomAccessFile))
    await runRandomizerStep(debug, 'close-working-source-random-access', () => callJavaMethod(randomAccessFile, 'close'))
    const ndsRom = await runRandomizerStep(
      debug,
      'probe-nds-rom-constructor',
      async () => {
        try {
          return await createJavaInstance(lib, ['com', 'dabomstew', 'pkrandom', 'newnds', 'NDSRom'], workingSourcePath)
        } catch (error) {
          throw new Error(await describeJavaError(error))
        }
      },
    )
    await runRandomizerStep(debug, 'probe-nds-arm9', async () => {
      try {
        return await callJavaMethod(ndsRom, 'getARM9')
      } catch (error) {
        throw new Error(await describeJavaError(error))
      }
    })
    await runRandomizerStep(debug, 'probe-nds-text-narc', async () => {
      try {
        return await callJavaMethod(ndsRom, 'getFile', 'msgdata/pl_msg.narc')
      } catch (error) {
        throw new Error(await describeJavaError(error))
      }
    })
    await runRandomizerStep(debug, 'probe-nds-script-narc', async () => {
      try {
        return await callJavaMethod(ndsRom, 'getFile', 'fielddata/script/scr_seq.narc')
      } catch (error) {
        throw new Error(await describeJavaError(error))
      }
    })
    await runRandomizerStep(debug, 'probe-nds-event-narc', async () => {
      try {
        return await callJavaMethod(ndsRom, 'getFile', 'fielddata/eventdata/zone_event.narc')
      } catch (error) {
        throw new Error(await describeJavaError(error))
      }
    })
    await runRandomizerStep(debug, 'close-probe-nds-rom', () => callJavaMethod(ndsRom, 'closeROM'))
    await runRandomizerStep(
      debug,
      'load-source-rom',
      async () => {
        try {
          return await callJavaMethod(romHandler, 'loadRom', workingSourcePath)
        } catch (error) {
          throw new Error(await describeJavaError(error))
        }
      },
      240000,
    )
    const settings = await runRandomizerStep(debug, 'parse-settings', () => loadJavaSettings(lib, normalizedSettingsString))
    await runRandomizerStep(debug, 'load-custom-names', async () => {
      const FileFunctions = await resolveJavaClass<{ getCustomNames: () => Promise<unknown> }>(
        lib,
        ['com', 'dabomstew', 'pkrandom', 'FileFunctions'],
      )
      const customNames = await FileFunctions.getCustomNames()
      return callJavaMethod(settings, 'setCustomNames', customNames)
    })
    await runRandomizerStep(debug, 'tweak-settings-for-rom', () => callJavaMethod(settings, 'tweakForRom', romHandler))
    const randomizer = await runRandomizerStep(debug, 'create-randomizer', () =>
      createJavaInstance(lib, ['com', 'dabomstew', 'pkrandom', 'Randomizer'], settings, romHandler),
    )
    await runRandomizerStep(
      debug,
      'run-randomizer',
      async () => {
        try {
          return await (randomizer as { randomize: (path: string) => Promise<number> }).randomize(outputPath)
        } catch (error) {
          throw new Error(await describeJavaError(error))
        }
      },
      240000,
    )
    const fileData = await runRandomizerStep(debug, 'read-randomized-rom-output', () => readRandomizedFile(lib, outputPath), 120000)
    completeRandomizerDebugState(debug)

    return {
      fileName: outputFileName,
      fileData,
      presetLabel: presetLabelOverride ?? presetConfig.label,
    }
  } catch (error) {
    recordRandomizerError(error)
    throw error
  } finally {
    restoreEmulatorHeapGlobals()
  }
}

function buildSourceFileName(romName: string): string {
  return `${romName.replace(/\.nds$/i, '')}-source.nds`
}

function buildOutputFileName(romName: string, preset: RandomizerPresetId): string {
  const stamp = new Date().toISOString().replace(/[:.]/g, '-')
  return `${romName.replace(/\.nds$/i, '')}-${preset}-${stamp}.nds`
}

export function decodePresetSettings(settingsBytes: Uint8Array): { version: number; settingsString: string } {
  const textDecoder = new TextDecoder('utf-8')

  // Older "settings string" exports were stored as a single version byte plus the base64 config string.
  if (settingsBytes.byteLength > 2 && settingsBytes[0] >= 100) {
    let payloadOffset = 1
    let settingsString = textDecoder.decode(settingsBytes.slice(payloadOffset)).trim()
    if (settingsString.length % 4 !== 0 && settingsBytes.byteLength > 3) {
      payloadOffset = 2
      settingsString = textDecoder.decode(settingsBytes.slice(payloadOffset)).trim()
    }

    return {
      version: settingsBytes[0],
      settingsString,
    }
  }

  const decodedText = textDecoder.decode(settingsBytes).trim()
  if (/^\d{3}/.test(decodedText)) {
    return {
      version: Number(decodedText.slice(0, 3)),
      settingsString: decodedText.slice(3),
    }
  }

  if (settingsBytes.byteLength < 8) {
    throw new Error('The bundled preset settings could not be decoded.')
  }

  const view = new DataView(settingsBytes.buffer, settingsBytes.byteOffset, settingsBytes.byteLength)
  const version = view.getInt32(0, false)
  const length = view.getInt32(4, false)

  if (length <= 0 || 8 + length > settingsBytes.byteLength) {
    throw new Error('The bundled preset settings have an invalid length header.')
  }

  return {
    version,
    settingsString: textDecoder.decode(settingsBytes.slice(8, 8 + length)),
  }
}

export function updateSettingsString(version: number, settingsString: string): string {
  if (version === RANDOMIZER_SETTINGS_VERSION) {
    return settingsString
  }

  if (version < 172) {
    throw new Error('Preset settings older than version 172 are not supported by this web build.')
  }

  const data = Uint8Array.from(atob(settingsString), (char) => char.charCodeAt(0))
  const dataBlock = new Uint8Array(200)
  dataBlock.set(data)
  let actualDataLength = data.length

  if (version < 300) {
    actualDataLength = insertExtraByte(dataBlock, actualDataLength, 38, 50)
    actualDataLength = insertExtraByte(dataBlock, actualDataLength, 39, 1)
  }

  if (version < 311) {
    actualDataLength = insertExtraByte(dataBlock, actualDataLength, 40, 0)
    actualDataLength = insertExtraByte(dataBlock, actualDataLength, 41, 8)
    actualDataLength = insertExtraByte(dataBlock, actualDataLength, 42, 9)
    actualDataLength = insertExtraByte(dataBlock, actualDataLength, 43, 50)
    actualDataLength = insertExtraByte(dataBlock, actualDataLength, 44, 0)
    actualDataLength = insertExtraByte(dataBlock, actualDataLength, 45, 0)
  }

  if (version < 314) {
    actualDataLength = insertExtraByte(dataBlock, actualDataLength, 46, 0)
    actualDataLength = insertExtraByte(dataBlock, actualDataLength, 47, 50)
  }

  if (version < 315) {
    const oldTweaks = readFullIntBigEndian(dataBlock, 32) & ~0x100
    writeFullIntBigEndian(dataBlock, 32, oldTweaks)
    actualDataLength = insertExtraByte(dataBlock, actualDataLength, 48, 0)
  }

  if (version < 317) {
    actualDataLength = insertExtraByte(dataBlock, actualDataLength, 49, 0)
    const genRestrictions = readFullIntBigEndian(dataBlock, 28) & 127
    writeFullIntBigEndian(dataBlock, 28, genRestrictions)
  }

  if (version < 319) {
    write2ByteInt(dataBlock, 5, read2ByteInt(dataBlock, 5) + 1)
    write2ByteInt(dataBlock, 7, read2ByteInt(dataBlock, 7) + 1)
    write2ByteInt(dataBlock, 9, read2ByteInt(dataBlock, 9) + 1)
    actualDataLength = insertExtraByte(dataBlock, actualDataLength, 50, 0)
  }

  if (version < 321) {
    const oldMinimumCatchRate = ((dataBlock[16] & 0x60) >> 5) + 1
    dataBlock[16] &= ~0x60
    dataBlock[50] |= (oldMinimumCatchRate - 1) << 3
  }

  const checksum = crc32(dataBlock.subarray(0, actualDataLength - 8))
  writeFullIntBigEndian(dataBlock, actualDataLength - 8, checksum)

  const finalConfigBytes = dataBlock.slice(0, actualDataLength)
  return btoa(String.fromCharCode(...finalConfigBytes))
}

function read2ByteInt(data: Uint8Array, offset: number): number {
  return (((data[offset] & 0xff) << 8) | (data[offset + 1] & 0xff)) >>> 0
}

function write2ByteInt(data: Uint8Array, offset: number, value: number): void {
  data[offset] = (value >> 8) & 0xff
  data[offset + 1] = value & 0xff
}

export function readFullIntBigEndian(data: Uint8Array, offset: number): number {
  return (
    ((data[offset] & 0xff) << 24) |
    ((data[offset + 1] & 0xff) << 16) |
    ((data[offset + 2] & 0xff) << 8) |
    (data[offset + 3] & 0xff)
  ) >>> 0
}

export function writeFullIntBigEndian(data: Uint8Array, offset: number, value: number): void {
  data[offset] = (value >>> 24) & 0xff
  data[offset + 1] = (value >>> 16) & 0xff
  data[offset + 2] = (value >>> 8) & 0xff
  data[offset + 3] = value & 0xff
}

function insertExtraByte(
  dataBlock: Uint8Array,
  actualDataLength: number,
  position: number,
  value: number,
): number {
  if (actualDataLength >= dataBlock.length) {
    return actualDataLength
  }

  for (let index = actualDataLength; index > position; index -= 1) {
    dataBlock[index] = dataBlock[index - 1]
  }

  dataBlock[position] = value & 0xff
  return actualDataLength + 1
}

export function crc32(data: Uint8Array): number {
  let crc = 0xffffffff

  for (let index = 0; index < data.length; index += 1) {
    crc = CRC32_TABLE[(crc ^ data[index]) & 0xff] ^ (crc >>> 8)
  }

  return (crc ^ 0xffffffff) >>> 0
}

function buildCrc32Table(): Uint32Array {
  const table = new Uint32Array(256)

  for (let index = 0; index < 256; index += 1) {
    let value = index
    for (let bit = 0; bit < 8; bit += 1) {
      value = (value & 1) !== 0 ? 0xedb88320 ^ (value >>> 1) : value >>> 1
    }
    table[index] = value >>> 0
  }

  return table
}

function injectLoaderScript(): Promise<void> {
  if (loaderPromise) {
    return loaderPromise
  }

  loaderPromise = new Promise((resolve, reject) => {
    const existing = document.querySelector<HTMLScriptElement>('script[data-cheerpj-loader="true"]')
    if (existing) {
      if (window.cheerpjInit) {
        resolve()
        return
      }

      existing.addEventListener('load', () => resolve(), { once: true })
      existing.addEventListener('error', () => reject(new Error('Could not load the browser randomizer runtime.')), { once: true })
      return
    }

    const script = document.createElement('script')
    script.src = CHEERPJ_LOADER_URL
    script.async = true
    script.dataset.cheerpjLoader = 'true'
    script.onload = () => resolve()
    script.onerror = () => reject(new Error('Could not load the browser randomizer runtime.'))
    document.head.appendChild(script)
  })

  return loaderPromise
}

async function ensureRuntimeReady(): Promise<CheerpJLibrary> {
  if (runtimePromise) {
    return runtimePromise
  }

  runtimePromise = (async () => {
    captureEmulatorHeapGlobals()

    try {
      await injectLoaderScript()

      if (!window.cheerpjInit) {
        throw new Error('The browser randomizer runtime is unavailable.')
      }

      await window.cheerpjInit()
      if (!window.cheerpjRunLibrary) {
        throw new Error('The browser randomizer library API is unavailable.')
      }
      return window.cheerpjRunLibrary(getRandomizerJarAppPath())
    } catch (error) {
      restoreEmulatorHeapGlobals()
      runtimePromise = null
      throw error
    }
  })()

  return runtimePromise
}

function getRandomizerJarAppPath(): string {
  const base = import.meta.env.BASE_URL.replace(/^\/+|\/+$/g, '')
  return base ? `/app/${base}/randomizer/dist/randomizer.jar` : '/app/randomizer/dist/randomizer.jar'
}

async function loadJavaSettings(lib: CheerpJLibrary, settingsString: string): Promise<unknown> {
  const Settings = await resolveJavaClass<{ fromString: (value: string) => Promise<unknown> }>(
    lib,
    ['com', 'dabomstew', 'pkrandom', 'Settings'],
  )
  return Settings.fromString(settingsString)
}

async function resolveJavaClass<T>(lib: CheerpJLibrary, path: string[]): Promise<T> {
  let current: unknown = lib

  for (const segment of path) {
    current = typeof current === 'object' && current !== null
      ? (current as Record<string, unknown>)[segment]
      : undefined
    if (current == null) {
      throw new Error(`Missing Java class export: ${path.join('.')}`)
    }
  }

  return current as T
}

async function createJavaInstance<T>(lib: CheerpJLibrary, path: string[], ...args: unknown[]): Promise<T> {
  const JavaClass = await resolveJavaClass<new (...ctorArgs: unknown[]) => T>(lib, path)
  return await new JavaClass(...args)
}

async function callJavaMethod<T>(instance: unknown, methodName: string, ...args: unknown[]): Promise<T> {
  const candidate = instance as Record<string, unknown>
  if (typeof candidate[methodName] !== 'function') {
    throw new Error(`Missing Java method: ${methodName}`)
  }

  return (candidate[methodName] as (...callArgs: unknown[]) => Promise<T> | T)(...args)
}

function captureEmulatorHeapGlobals(): void {
  if (emulatorHeapGlobalsSnapshot) {
    return
  }

  const globalWindow = window as unknown as Record<string, unknown>
  emulatorHeapGlobalsSnapshot = {}

  for (const key of EMULATOR_HEAP_GLOBAL_KEYS) {
    emulatorHeapGlobalsSnapshot[key] = globalWindow[key]
  }
}

function restoreEmulatorHeapGlobals(): void {
  if (!emulatorHeapGlobalsSnapshot) {
    return
  }

  const globalWindow = window as unknown as Record<string, unknown>

  for (const key of EMULATOR_HEAP_GLOBAL_KEYS) {
    const value = emulatorHeapGlobalsSnapshot[key]
    if (value !== undefined) {
      globalWindow[key] = value
    }
  }
}

function createRandomizerDebugState({
  preset,
  romName,
  romBytes,
}: {
  preset: RandomizerPresetId
  romName: string
  romBytes: number
}): RandomizerDebugState {
  const now = new Date().toISOString()
  const state: RandomizerDebugState = {
    startedAt: now,
    updatedAt: now,
    phase: 'running',
    currentStep: 'initializing',
    completedSteps: [],
    error: null,
    preset,
    romName,
    romBytes,
    telemetry: readRuntimeTelemetry(),
  }
  persistRandomizerDebugState(state)
  return state
}

function completeRandomizerDebugState(state: RandomizerDebugState): void {
  state.phase = 'completed'
  state.currentStep = 'completed'
  state.updatedAt = new Date().toISOString()
  state.telemetry = readRuntimeTelemetry()
  persistRandomizerDebugState(state)
}

function recordRandomizerError(error: unknown): void {
  const existing = readPersistedRandomizerDebugState()
  if (!existing) {
    return
  }

  existing.phase = 'failed'
  existing.error = error instanceof Error ? error.message : String(error)
  existing.updatedAt = new Date().toISOString()
  existing.telemetry = readRuntimeTelemetry()
  persistRandomizerDebugState(existing)
}

async function runRandomizerStep<T>(
  state: RandomizerDebugState,
  stepName: string,
  action: () => Promise<T> | T,
  timeoutMs = 45000,
): Promise<T> {
  state.currentStep = stepName
  state.updatedAt = new Date().toISOString()
  state.telemetry = readRuntimeTelemetry()
  persistRandomizerDebugState(state)
  debugLog(`[randomizer] step:start ${stepName}`, state.telemetry)

  try {
    const result = await withTimeout(action(), timeoutMs, `Timed out during ${stepName}.`)
    state.completedSteps = [...state.completedSteps, stepName]
    state.updatedAt = new Date().toISOString()
    state.telemetry = readRuntimeTelemetry()
    persistRandomizerDebugState(state)
    debugLog(`[randomizer] step:done ${stepName}`, state.telemetry)
    return result
  } catch (error) {
    state.phase = 'failed'
    state.error = error instanceof Error ? error.message : String(error)
    state.updatedAt = new Date().toISOString()
    state.telemetry = readRuntimeTelemetry()
    persistRandomizerDebugState(state)
    console.error(`[randomizer] step:failed ${stepName}: ${state.error}`)
    throw error
  }
}

function persistRandomizerDebugState(state: RandomizerDebugState): void {
  window.localStorage.setItem(RANDOMIZER_DEBUG_KEY, JSON.stringify(state))
}

function readPersistedRandomizerDebugState(): RandomizerDebugState | null {
  const raw = window.localStorage.getItem(RANDOMIZER_DEBUG_KEY)
  if (!raw) {
    return null
  }

  try {
    return JSON.parse(raw) as RandomizerDebugState
  } catch {
    return null
  }
}

function readRuntimeTelemetry(): RandomizerDebugState['telemetry'] {
  const globalWindow = window as Window & {
    Module?: {
      HEAP8?: { length?: number }
    }
    HEAP8?: { length?: number }
  }
  const perfMemory = (performance as Performance & {
    memory?: {
      jsHeapSizeLimit?: number
      usedJSHeapSize?: number
      totalJSHeapSize?: number
    }
  }).memory

  return {
    moduleHeap8Length: typeof globalWindow.Module?.HEAP8?.length === 'number' ? globalWindow.Module.HEAP8.length : null,
    windowHeap8Length: typeof globalWindow.HEAP8?.length === 'number'
      ? globalWindow.HEAP8.length
      : null,
    jsHeapLimit: perfMemory?.jsHeapSizeLimit ?? null,
    usedJsHeapSize: perfMemory?.usedJSHeapSize ?? null,
    totalJsHeapSize: perfMemory?.totalJSHeapSize ?? null,
  }
}

function withTimeout<T>(promise: Promise<T> | T, timeoutMs: number, message: string): Promise<T> {
  return new Promise<T>((resolve, reject) => {
    const timeoutId = window.setTimeout(() => {
      reject(new Error(message))
    }, timeoutMs)

    Promise.resolve(promise).then(
      (value) => {
        window.clearTimeout(timeoutId)
        resolve(value)
      },
      (error) => {
        window.clearTimeout(timeoutId)
        reject(error)
      },
    )
  })
}

export async function loadPresetSettings(path: string): Promise<Uint8Array> {
  const controller = new AbortController()
  const timeoutId = window.setTimeout(() => controller.abort(), 10000)
  const basePath = `${import.meta.env.BASE_URL}${path}`.replace(/\/{2,}/g, '/')
  const presetUrl = new URL(basePath, window.location.origin).toString()
  const response = await fetch(
    `${presetUrl}${presetUrl.includes('?') ? '&' : '?'}t=${Date.now()}`,
    {
      cache: 'no-store',
      signal: controller.signal,
    },
  ).finally(() => {
    window.clearTimeout(timeoutId)
  })
  if (!response.ok) {
    throw new Error(`Could not load preset settings (${response.status}).`)
  }

  return new Uint8Array(await response.arrayBuffer())
}

async function clearRandomizerStorage(): Promise<void> {
  await Promise.all(['/files', 'cjFS_/files/'].map(deleteDatabase))
}

function deleteDatabase(name: string): Promise<void> {
  return new Promise((resolve) => {
    const request = indexedDB.deleteDatabase(name)
    request.onerror = () => resolve()
    request.onblocked = () => resolve()
    request.onsuccess = () => resolve()
  })
}

async function readRandomizedFile(lib: CheerpJLibrary, path: string): Promise<Uint8Array> {
  const File = await resolveJavaClass<new (path: string) => {
    length: () => Promise<number>
  }>(lib, ['java', 'io', 'File'])
  const FileInputStream = await resolveJavaClass<new (path: string) => {
    read: (buffer: Int8Array, offset: number, length: number) => Promise<number>
    close: () => Promise<void>
  }>(lib, ['java', 'io', 'FileInputStream'])

  const file = await new File(path)
  const length = Number(await file.length())
  if (!Number.isFinite(length) || length <= 0) {
    throw new Error('The randomized ROM output file was empty.')
  }

  const fileInput = await new FileInputStream(path)
  const fileData = new Int8Array(length)
  let offset = 0

  try {
    while (offset < fileData.length) {
      const bytesRead = Number(await fileInput.read(fileData, offset, fileData.length - offset))
      if (bytesRead <= 0) {
        throw new Error(`Stopped reading randomized ROM output at ${offset} bytes.`)
      }

      offset += bytesRead
    }
  } finally {
    await fileInput.close().catch(() => undefined)
  }

  return new Uint8Array(fileData.buffer.slice(0))
}

async function describeJavaError(error: unknown): Promise<string> {
  if (error instanceof Error && error.message) {
    return error.message
  }

  const details: string[] = []

  if (error && (typeof error === 'object' || typeof error === 'function')) {
    try {
      const message = await callJavaMethod<string>(error, 'toString')
      if (message) {
        details.push(String(message))
      }
    } catch {
      // Ignore Java proxy string conversion failures.
    }

    try {
      const cause = await callJavaMethod<unknown>(error, 'getCause')
      if (cause) {
        const causeString = await callJavaMethod<string>(cause, 'toString')
        if (causeString) {
          details.push(`cause: ${String(causeString)}`)
        }
      }
    } catch {
      // Ignore Java proxy cause lookup failures.
    }
  }

  return details.join(' | ') || 'Unknown Java exception.'
}

async function verifyWorkingSourceHeader(randomAccessFile: unknown): Promise<void> {
  const code = await readAscii(randomAccessFile, 0x0c, 4)
  const arm9Offset = await readUint32LE(randomAccessFile, 0x20)
  const arm9Size = await readUint32LE(randomAccessFile, 0x2c)

  if (code !== 'CPUE' || arm9Offset !== 16384 || arm9Size !== 1057784) {
    throw new Error(
      `Unexpected staged ROM header: code=${code} arm9Offset=${String(arm9Offset)} arm9Size=${String(arm9Size)}`,
    )
  }
}

async function stageWorkingSourceFile(lib: CheerpJLibrary, path: string, romData: Uint8Array): Promise<void> {
  const FileOutputStream = await resolveJavaClass<new (path: string) => {
    write: (data: Int8Array, offset: number, length: number) => Promise<void>
    close: () => Promise<void>
  }>(lib, ['java', 'io', 'FileOutputStream'])

  const outputStream = await new FileOutputStream(path)
  const chunkSize = 1024 * 1024
  const progressInterval = 8 * 1024 * 1024
  let nextProgressOffset = 0

  try {
    for (let offset = 0; offset < romData.byteLength; offset += chunkSize) {
      const length = Math.min(chunkSize, romData.byteLength - offset)
      const chunk = new Int8Array(romData.buffer, romData.byteOffset + offset, length)
      await outputStream.write(chunk, 0, length)

      if (offset >= nextProgressOffset) {
        debugLog('[randomizer] staged source bytes', offset)
        nextProgressOffset += progressInterval
      }

      if ((offset / chunkSize) % 16 === 0) {
        await new Promise((resolve) => window.setTimeout(resolve, 0))
      }
    }
  } finally {
    await outputStream.close()
  }
}

async function readAscii(file: unknown, offset: number, length: number): Promise<string> {
  await callJavaMethod(file, 'seek', offset)
  const chars: string[] = []
  for (let index = 0; index < length; index += 1) {
    const value = Number(await callJavaMethod(file, 'readUnsignedByte'))
    chars.push(String.fromCharCode(value))
  }
  return chars.join('')
}

async function readUint32LE(file: unknown, offset: number): Promise<number> {
  await callJavaMethod(file, 'seek', offset)
  const b0 = Number(await callJavaMethod(file, 'readUnsignedByte'))
  const b1 = Number(await callJavaMethod(file, 'readUnsignedByte'))
  const b2 = Number(await callJavaMethod(file, 'readUnsignedByte'))
  const b3 = Number(await callJavaMethod(file, 'readUnsignedByte'))
  return ((b0 & 0xff) | ((b1 & 0xff) << 8) | ((b2 & 0xff) << 16) | ((b3 & 0xff) << 24)) >>> 0
}
